# Math  1376: Programming for Data Science
---

## Assignment 02 (part b): `numpy` and array manipulation (due by 11:59 p.m. Friday of week 4 of class)
---

Much of this assignment makes use of the following arrays. Some problems will involve creating new arrays as well.

In [1]:
import numpy as np

In [2]:
array_1 = np.array([1, 2, 3])

array_2 = np.array([[1], [2], [3]])

array_3 = np.array([[1, 2, 3], [4, 5, 6]])

array_4 = np.array([[[1, 2], [3, 4], [5, 6]]])

array_5 = np.array([[ [1], [2] ], [ [3], [4] ], [ [5], [6] ]])

You may also find the following documentation quite useful: https://numpy.org/doc/1.18/reference/routines.array-manipulation.html

## Problem 1: Array shapes and addition
---

Try running each of the following individual code cells and explain (1) the conditions under which two arrays may be added and (2) what array addition does in the following Markdown cell.

We make use of the `try` and `except` commands to handle errors. Read more about these here: https://docs.python.org/3/tutorial/errors.html. We simply do this to get you used to the idea that you can handle potential errors and give feedback to users that is perhaps more informative/relevant.


*You should change the feedback given to the user if there is an error.* What feedback should you give? Try seeing what the actual `ValueError` is that is returned and make sense of it. How could this be made more informative? Perhaps make use of the `np.shape` commands to make a verbose print out of what went wrong.

In [3]:
try:
    array_sum = array_1 + array_2
    print(array_sum)
except ValueError:
    print('Can\'t sum those!')

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [4]:
try:
    array_sum = array_1 + array_3
    print(array_sum)
except ValueError:
    print('Can\'t sum those!')

[[2 4 6]
 [5 7 9]]


In [5]:
try:
    array_sum = array_2 + array_3
    print(array_sum)
except ValueError:
    print('Can\'t sum those!')

Can't sum those!


In [ ]:
try:
    array_sum = array_2 + array_4
    print(array_sum)
except ValueError:
    print('Can\'t sum those!')

In [ ]:
try:
    array_sum = array_4 + array_5
    print(array_sum)
except ValueError:
    print('Can\'t sum those!')

In [ ]:
try:
    array_sum = array_1 + array_5
    print(array_sum)
except ValueError:
    print('Can\'t sum those!')

In [ ]:
try:
    array_sum = array_2 + array_5
    print(array_sum)
except ValueError:
    print('Can\'t sum those!')

In [ ]:
try:
    array_sum = array_2.T + array_5
    print(array_sum)
except ValueError:
    print('Can\'t sum those!')

In [ ]:
try:
    array_sum = array_3 + array_5
    print(array_sum)
except ValueError:
    print('Can\'t sum those!')

## Problem 2: Array shapes and multiplication
---

Try running each of the following individual code cells and explain (1) the conditions under which two arrays may be multiplied using either `*` or `np.multiply` and (2) what this type of array multiplication does in the following Markdown cell.

Also, re-write each of these code cells to make use of the `try` and `except` functions like above where some relevant feedback is given to the user about what went wrong if there is a `ValueError`.

In [6]:
array_1 * array_1

array([1, 4, 9])

In [7]:
array_1 * array_2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [8]:
array_1 * array_3

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [9]:
array_1 * array_4

ValueError: operands could not be broadcast together with shapes (3,) (1,3,2) 

In [10]:
array_1 * array_4.T

array([[[ 1,  2,  3],
        [ 3,  6,  9],
        [ 5, 10, 15]],

       [[ 2,  4,  6],
        [ 4,  8, 12],
        [ 6, 12, 18]]])

In [11]:
array_1.T * array_4

ValueError: operands could not be broadcast together with shapes (3,) (1,3,2) 

In [12]:
array_2 * array_3

ValueError: operands could not be broadcast together with shapes (3,1) (2,3) 

In [13]:
array_2.T * array_3

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [14]:
array_2 * array_3.T

array([[ 1,  4],
       [ 4, 10],
       [ 9, 18]])

In [15]:
array_3.T * array_5

ValueError: operands could not be broadcast together with shapes (3,2) (3,2,1) 

## Problem 3: Manipulating array shapes
---

### Part (a): [reshape](https://numpy.org/doc/1.18/reference/generated/numpy.reshape.html#numpy.reshape)

Use the markdown cell below to explain what is going on in the next code cell. Look at some of the comments in the code below for inspiration about what to discuss.

In [ ]:
print(array_1)
print()

print(array_1.reshape((3,1))) #compare to array_2
print()

print(array_1.reshape((1,3)))
print()

print(array_1) #did reshape change the array like certain list operations (e.g., reverse) changed the list in the last assignment?
print()

print(array_2)
print()

print(array_2.reshape((3,))) #compare to array_1

### Part (b): [ravel](https://numpy.org/doc/1.18/reference/generated/numpy.ravel.html#numpy.ravel) vs [flatten](https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten)

Run the code cells below. Do a bit of digging/reading about `ravel` vs `flatten` in `numpy`. What is happening? Explain in the markdown cell following these code cells. Try describing some scenarios where you may want to use `ravel` over `flatten` and vice versa.

In [ ]:
print(array_4.ravel())
print()

print(array_4.flatten())
print()

print(array_4)

In [ ]:
array_4.ravel()[1] = 7
print(array_4.ravel())
print()
print(array_4)
print()

array_4.ravel()[1] = 2
print(array_4.ravel())
print()
print(array_4)
print()

In [ ]:
array_4.flatten()[1] = 7
print(array_4.flatten())
print()
print(array_4)

## Problem 4: Combining arrays

### Part (a) [hstack](https://numpy.org/doc/1.18/reference/generated/numpy.hstack.html#numpy.hstack)

Run the code cells below. Interpret what is happening in the Markdown cell following these code cells. Provide some better feedback than just `Can't do that!` if there is an error. For instance, maybe let the user know more about what went wrong. To figure that out, you may first need to decipher the `ValueError` by running the commands without the `try`.

In [ ]:
try:
    my_arrays = np.hstack((array_1, array_2))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.hstack((array_1, array_2.T))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.hstack((array_1, array_2.ravel()))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.hstack((array_1.reshape((3,1)), array_2))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.hstack((array_1.reshape((3,1)), array_3))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.hstack((array_1.reshape((3,1)), array_3.T))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

### Part (b): [vstack](https://numpy.org/doc/1.18/reference/generated/numpy.vstack.html)

Run the code cells below. Interpret what is happening in the Markdown cell following these code cells. Provide some better feedback if there is an error.

In [ ]:
try:
    my_arrays = np.vstack((array_1, array_2))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.vstack((array_1, array_2.T))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.vstack((array_1, array_2.ravel()))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.vstack((array_1.reshape((3,1)), array_2))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.vstack((array_1.reshape((1,3)), array_3))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

In [ ]:
try:
    my_arrays = np.vstack((array_1.reshape((1,3)), array_3.T))
    print(my_arrays)
except ValueError:
    print('Can\'t do that!')

## Problem 5:  [What's happening?!](https://www.youtube.com/watch?v=X0dcZ66783k)

Run the code cells below. Edit/add more useful comments and interpret what is happening in the Markdown cell that follows.

In [ ]:
list_1 = ['hi', 1, 2]

list_1_as_array = np.asarray(list_1)

print(list_1_as_array)
print()

print(list_1_as_array[1:]) #some slicing
print()
print(list_1_as_array[1] + list_1_as_array[2]) #adding two elements together of numpy array
print()
print(list_1[1] + list_1[2])

In [ ]:
np.sum(list_1[1:])

In [ ]:
np.sum(list_1_as_array[1:]) #Use a try and except command instead (except what though? Look at the TYPE of ERROR <--- hint)

## Problem 6: What is good in life?

Asking your own questions. Investigating things that are interesting to you. Being your own boss...

There are so many other things we are not going to cover. You should play around with some other methods available to you in `numpy` for manipulating arrays. Check out the [documentation](https://numpy.org/doc/1.18/reference/routines.array-manipulation.html). Think about what you want to do. Maybe you want to `append` an array like we did to lists? ***Pick at least three manipulations we have not yet investigated above***  and write some code showing how to utilize them along with a brief interpretation of results in a Markdown cell. How deeply you investigate is completely up to you. If you want some suggestions: compare `tile` and `repeat`, compare `flip` to the list method `reverse`, the split methods are also interesting. 